apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2025-11-17T15:08:17.778835286Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: b25b53d53758088040e310128724228817c4ecfa39fc3aa3f1b554d316509a48
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2025-11-17T15:08:17.777182009Z"
