apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2026-01-30T15:55:21.048839302Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: c62dacbf53550f8d362e4dacd73a4bd0dbc4b354fad40f8ac6d47a3c03797298
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2026-01-30T15:55:21.047054072Z"
