apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2026-01-05T14:22:53.660929512Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: e5ef5e44b649b2770ebdecff6d6e6eb5a666d0138c489d304f7aaf0e3b53e722
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2026-01-05T14:22:53.659836537Z"
