apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2026-01-30T15:50:49.479776683Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: 927e439afe44b8486fa5ae1f3562cd830f6d28dad6fa9c42b86fc656ceb4730e
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2026-01-30T15:50:49.478685677Z"
