apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2026-02-18T09:48:57.412474689Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: 9a29fe8344c1ed6f2864891de9dd00fe00dd499f3a94b462838d15a33ef04ba6
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2026-02-18T09:48:57.411199679Z"
