apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2026-01-27T19:48:22.285926701Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: 386f49e6f8297fcaa437b2780e55bf29e735ae17369a0e7c64d298f954b6fb49
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2026-01-27T19:48:22.284842187Z"
