apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2026-01-27T19:47:49.919933372Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: 5983fb8505e0c3b897fe6f828b4cca465dbf0c0d50a3704fb3779024c3a8771c
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2026-01-27T19:47:49.917478977Z"
