apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2026-02-10T01:37:28.080238704Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: 736e971083020bae42f07a89bf185933f01455a0144eb9d96ac9a6ee12cf1496
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2026-02-10T01:37:28.078834375Z"
