apiVersion: v1
entries:
  sourcify:
  - apiVersion: v2
    created: "2025-12-22T13:51:46.258392912Z"
    description: Helm chart of [hashgraph/hedera-sourcify](https://github.com/hashgraph/hedera-sourcify)
      repository service.
    digest: 8f91d6e671696ad5416e57205afb4f255c8ed70042ff242b0200ba462296ae95
    name: sourcify
    type: application
    urls:
    - https://hashgraph.github.io/hedera-sourcify/charts/sourcify-0.4.0-SNAPSHOT.tgz
    version: 0.4.0-SNAPSHOT
generated: "2025-12-22T13:51:46.257239825Z"
